# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('grant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='授权ID')),
            ],
            options={
                'verbose_name': 'Grant',
                'db_table': 'T_GRANT',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('privilege_id', models.AutoField(primary_key=True, serialize=False, verbose_name='权限ID')),
                ('privilege_name', models.CharField(max_length=30, verbose_name='权限名称')),
                ('pri_create', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], default=0, verbose_name='创建权限')),
                ('pri_delete', models.IntegerField(blank=True, choices=[(0, '否'), (2, '是')], default=0, verbose_name='删除权限')),
                ('pri_access', models.IntegerField(blank=True, choices=[(0, '否'), (4, '是')], default=0, verbose_name='访问权限')),
                ('pri_modify', models.IntegerField(blank=True, choices=[(0, '否'), (8, '是')], default=0, verbose_name='修改权限')),
                ('pri_import', models.IntegerField(blank=True, choices=[(0, '否'), (16, '是')], default=0, verbose_name='导入权限')),
                ('pri_export', models.IntegerField(blank=True, choices=[(0, '否'), (32, '是')], default=0, verbose_name='导出权限')),
                ('extend_1', models.IntegerField(blank=True, choices=[(0, '否'), (64, '是')], default=0, verbose_name='扩展权限1')),
                ('extend_2', models.IntegerField(blank=True, choices=[(0, '否'), (128, '是')], default=0, verbose_name='扩展权限2')),
                ('extend_3', models.IntegerField(blank=True, choices=[(0, '否'), (256, '是')], default=0, verbose_name='扩展权限3')),
                ('extend_4', models.IntegerField(blank=True, choices=[(0, '否'), (512, '是')], default=0, verbose_name='扩展权限4')),
            ],
            options={
                'verbose_name': 'Privilege',
                'db_table': 'T_PRIVILEGE',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False, verbose_name='资源id')),
                ('res_type', models.IntegerField(verbose_name='资源类型')),
                ('res_name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('res_url', models.CharField(max_length=1024, verbose_name='资源url')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name='资源状态')),
                ('extend_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='扩展字段1')),
                ('extend_2', models.CharField(blank=True, max_length=64, null=True, verbose_name='扩展字段2')),
                ('extend_3', models.CharField(blank=True, max_length=128, null=True, verbose_name='扩展字段3')),
                ('extend_4', models.CharField(blank=True, max_length=128, null=True, verbose_name='扩展字段4')),
                ('extend_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展字段5')),
                ('child_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_resource', to='author.Resource', verbose_name='子节点')),
            ],
            options={
                'verbose_name': 'Resource',
                'db_table': 'T_RESOURCE',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_code', models.AutoField(primary_key=True, serialize=False, verbose_name='角色编码')),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 1, 11, 13, 43, 832107), verbose_name='创建时间')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Role',
                'db_table': 'T_ROLE',
            },
        ),
        migrations.CreateModel(
            name='RolePrivilege',
            fields=[
                ('role_pri_id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色权限ID')),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_m1_privilege', to='author.Privilege', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_m2_privilege', to='author.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': 'RolePrivilege',
                'db_table': 'T_ROLE_PRIVILEGE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('login_id', models.CharField(max_length=30, unique=True, verbose_name='登陆名')),
                ('password', models.CharField(max_length=32, verbose_name='登陆密码')),
                ('real_name', models.CharField(max_length=60, verbose_name='真实姓名')),
                ('status', models.IntegerField(choices=[(0, '启用'), (1, '冻结')], default=0, verbose_name='状态')),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 1, 11, 13, 43, 831106), verbose_name='注册时间')),
                ('portrait', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户头像')),
                ('territory', models.CharField(blank=True, max_length=50, null=True, verbose_name='领域')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('province_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='省份id')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='等级')),
                ('extend_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展1')),
                ('extend_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展2')),
                ('extend_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展3')),
                ('extend_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展4')),
                ('extend_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='扩展5')),
                ('extend_6', models.BooleanField(default=False, verbose_name='扩展6')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to='author.User', verbose_name='注册人')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_user', to='author.User', verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'T_USER',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户角色ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m1_role', to='author.Role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m2_role', to='author.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'UserRole',
                'db_table': 'T_USER_ROLE',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_creator', to='author.User', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='role',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_updater', to='author.User', verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='res_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_resource', to='author.Resource', verbose_name='资源ID'),
        ),
        migrations.AddField(
            model_name='grant',
            name='privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_privilege', to='author.Privilege', verbose_name='授权'),
        ),
        migrations.AddField(
            model_name='grant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grant', to='author.User', verbose_name='用户'),
        ),
    ]
