# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 1, 11, 13, 51, 217912), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 1, 11, 13, 51, 214895), verbose_name='注册时间'),
        ),
    ]
